---
title: "Get Started with futebolplotR"
description:
author: "Bruno Mioto & Gabriela Junqueira"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  dpi = 600
)
```

#> fazer uma intro

# Install the Package

The easiest way to get `FutebolplotR` is to install it from with:

```{r eval = FALSE}
if (!require("pak")) install.packages("pak")
pak::pak("brunomioto/futebolplotR")
```

#> fazer uma intro

```{r setup}
library(futebolplotR)
library(ggplot2)
library(dplyr)
# library(tidyverse)
library(brasileirao)
```

#> fazer uma intro


```{r}
# team <- futebolplotR::valid_team_names()

# data("matches")
matches_br <- brasileirao::matches
season_2023 <- dplyr::filter(matches_br, season == 2023)
season_2023 <- brasileirao::add_variables(season_2023)

season_2023_home <- season_2023 %>%
    group_by(home) %>%
    mutate(total_home_points = sum(home_points)) %>%
    mutate(goal_concede_home = sum(as.numeric(away_score))) %>%
    mutate(goal_scored_home = sum(as.numeric(home_score))) %>%
    ungroup() %>%
    slice(1:20) %>%
    select(home, home_abbr, total_home_points, goal_concede_home, goal_scored_home) %>%
    rename(fc = home)

season_2023_away <- season_2023 %>%
    group_by(away) %>%
    mutate(total_away_points = sum(away_points)) %>%
    mutate(goal_concede_away = sum(as.numeric(home_score))) %>%
    mutate(goal_scored_away = sum(as.numeric(away_score))) %>%
    ungroup() %>%
    slice(1:20) %>%
    select(away, total_away_points, goal_concede_away, goal_scored_away) %>%
    rename(fc = away)


df_teams <- left_join(season_2023_home, season_2023_away, by = "fc") %>%
    group_by(fc) %>%
    mutate(goals_concede = sum(goal_concede_home, goal_concede_away)) %>%
    mutate(goals_scored = sum(goal_scored_home, goal_scored_away)) %>%
    mutate(goals_difference = goals_scored - goals_concede) %>%
    ungroup()
```

#> fazer uma intro

```{r}
ggplot(df_teams, aes(x = total_home_points, y = total_away_points)) +
  geom_abline()+
  futebolplotR::geom_futebol_badges(aes(team_abbr = home_abbr), width = 0.064, alpha = 0.8) +
  labs(
    x = "Points home",
    y = "Points away",
    caption = "Data: @brasileirao",
    title = "Campeonato Brasileiro 2023"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold"),
    plot.title.position = "plot"
  ) +
  coord_fixed(
    xlim = c(5,45),
    ylim = c(5,45)
  )
```

```{r}
ggplot(df_teams, aes(x = reorder(home_abbr,goals_scored), 
                              y = goals_scored)) +
  geom_col(aes(color = home_abbr, fill = home_abbr), width = 0.5) +
  futebolplotR::scale_color_futebol(type = "secondary") +
  futebolplotR::scale_fill_futebol() +
  labs(
    title = "Campeonato Brasileiro 2023",
    y = "Goals Scored",
    caption = "Data: @brasileirao"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold"),
    plot.title.position = "plot",
    axis.title.x = element_blank(),
    axis.text.x = futebolplotR::element_futebol_badge(size = 0.8)
  )
```

```{r}
ggplot(df_teams, aes(x = reorder(home_abbr,goals_difference),
                              y = goals_difference)) +
  geom_col(aes(color = home_abbr, fill = home_abbr), width = 0.5) +
  futebolplotR::scale_color_futebol(type = "secondary") +
  futebolplotR::scale_fill_futebol() +
  labs(
    title = "Compeonato Brasileiro 2023",
    y = "Goals difference"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(face = "bold"),
    plot.title.position = "plot",
    axis.title.x = element_blank(),
    #this line triggers the replacement of team abbreviations with logos
    axis.text.x = futebolplotR::element_futebol_badge(size = 0.8)
  )
```
